name: Builder

on:
  pull_request:
    branches:
      - main
    paths:
      - 'tailscale/**'
      - '.github/workflows/builder.yaml'

jobs:
  prepare:
    runs-on: ubuntu-24.04
    name: Prepare build matrix
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      version: ${{ fromJSON(steps.info.outputs.version) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Get add-on information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./tailscale"

      - name: Prepare multi-arch matrix
        id: matrix
        uses: home-assistant/builder/actions/prepare-multi-arch-matrix@2026.03.2
        with:
          architectures: '["aarch64", "amd64"]'
          image-name: app-tailscale

  build:
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.arch }} tailscale add-on
    needs: prepare
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Build tailscale add-on
        uses: home-assistant/builder/actions/build-image@2026.03.2
        with:
          arch: ${{ matrix.arch }}
          image: ${{ matrix.image }}
          image-tags: ${{ needs.prepare.outputs.version }}
          version: ${{ needs.prepare.outputs.version }}
          context: tailscale
          push: false
